[package]
name = "pepePong_Move"
version = "1.0.0"
authors = []

[addresses]
pong_addr = "xxx"
std = "0x1"
aptos_framework = "0x1"

[dev-addresses]

[dependencies]
#AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
#AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib", rev = "devnet" }
AptosFramework = { local = "/home/cxgd/opensourcePj/pingPong_Move/aptos-core/aptos-move/framework/aptos-framework" }
AptosStdlib = { local = "/home/cxgd/opensourcePj/pingPong_Move/aptos-core/aptos-move/framework/aptos-stdlib" }
[dev-dependencies]
